### ISSUE TITLE
Change the Heading with font

### ISSUE THREAD

**Issue by rakaar** [mask-tech/kaneki#3]
In the first part of the page change the heading to `Manga & Anime Society Kharagpur` with font of a japanese feel. I particularly liked [this](https://www.1001fonts.com/manga-temple-font.html#more). You can look for more [here](https://www.1001fonts.com/japanese-fonts.html). You can search from other sites if you want. Here is one [ref](https://www.pagecloud.com/blog/how-to-add-custom-fonts-to-any-website) to add custom font to your website.

**Comment by amarjeetrao** [comment]
I can help in that

**Comment by amarjeetrao** [comment]
hey @rakaar I have updated the requirements review the PR #17

**Comment by rakaar** [comment]
#17 solves this issue
