### ISSUE TITLE
Add a Contact us Section in the footer

### ISSUE THREAD

**Issue by Shankusu993** [mask-tech/kaneki#30]
modify the footer to show MASK contact details, which includes:
* FB
* Email
* phone

all details avalible from MASK's About  section in FB

**Comment by 1880akshay** [comment]
I am working on this issue but I am not able to find the phone number. Please provide the same

**Comment by PrabhuKGP** [comment]
@Shankusu993  pls check PR no. 38

**Comment by Shankusu993** [comment]
please assign the issues you work on before starting the work so clashes can be avoided. 
#38  solved the issue hence I'm closing this one here.
