### ISSUE TITLE
Replace the MASK in the navbar with Logo

### ISSUE THREAD

**Issue by rakaar** [mask-tech/kaneki#4]
Place a transaprent logo on the leftside of the navbar. Adjust its width in so as to good look in both in desktop as well as mobile views, preferably in percentage.

**Comment by rakaar** [comment]
@Shankusu993  can we get the logo

**Comment by 1880akshay** [comment]
I have replaced the text with the logo in the navbar. Please have a look on the PR I made just now.

**Comment by Shankusu993** [comment]
resolved in #36
