### ISSUE TITLE
Add a link to form for sending fan arts

### ISSUE THREAD

**Issue by rakaar** [mask-tech/kaneki#7]
In the site, where it is written  *UI, UX, visual*, replace with content telling people to send fan art. And the button `Get in touch` should link to the form with appropraite replaceable text on button.

**Comment by rakaar** [comment]
@Shankusu993  Can you provide the form link here

**Comment by Shankusu993** [comment]
https://forms.gle/PRavQ9NSMKzJR5mh9

**Comment by rakaar** [comment]
#16 solves this
